# Generated by Django 5.2.6 on 2025-09-12 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('codigo_interno', models.CharField(blank=True, max_length=50, null=True)),
                ('equipo', models.CharField(max_length=255)),
                ('marca', models.CharField(max_length=255)),
                ('modelo', models.CharField(max_length=255)),
                ('unidad', models.CharField(max_length=10)),
                ('extraccion', models.BooleanField(default=True)),
                ('host', models.CharField(blank=True, max_length=255, null=True)),
                ('puerto', models.CharField(blank=True, max_length=255, null=True)),
                ('baudios', models.IntegerField(default=9600)),
                ('pais', models.CharField(max_length=255)),
                ('sede', models.CharField(blank=True, max_length=255, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('formato', models.CharField(blank=True, max_length=100, null=True)),
                ('creador', models.CharField(max_length=255)),
                ('update', models.DateTimeField(blank=True, null=True)),
                ('update_user', models.CharField(blank=True, max_length=255, null=True)),
                ('bytesize', models.IntegerField(blank=True, null=True)),
                ('parity', models.CharField(blank=True, max_length=5, null=True)),
                ('stopbits', models.CharField(blank=True, max_length=3, null=True)),
                ('max_value', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'liis_equipo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muestra', models.CharField(max_length=255)),
                ('idve', models.CharField(max_length=255)),
                ('medida', models.CharField(max_length=10)),
                ('host', models.CharField(max_length=255, null=True)),
                ('ip_host', models.CharField(max_length=255, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('creador', models.CharField(max_length=255)),
                ('enviado', models.BooleanField(default=False, null=True)),
                ('equipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='liis.equipo')),
            ],
            options={
                'db_table': 'liis_medicion',
                'managed': True,
            },
        ),
    ]
