# Generated by Django 5.2.6 on 2025-09-13 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Países',
                'db_table': 'masshunter_pais',
            },
        ),
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(max_length=100)),
                ('nombre_reporte', models.CharField(max_length=100)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masshunter.pais')),
            ],
            options={
                'db_table': 'masshunter_instrumento',
                'unique_together': {('pais', 'nombre_equipo')},
            },
        ),
        migrations.CreateModel(
            name='Metodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_inyeccion', models.CharField(max_length=100)),
                ('metodo_reporte', models.CharField(max_length=100)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masshunter.pais')),
            ],
            options={
                'db_table': 'masshunter_metodo',
                'unique_together': {('pais', 'metodo_inyeccion')},
            },
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_cuantificacion', models.CharField(max_length=255)),
                ('idve_metodo', models.CharField(max_length=100)),
                ('fila_inicio_analitos', models.IntegerField()),
                ('fila_fin_analitos', models.IntegerField()),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masshunter.instrumento')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masshunter.pais')),
            ],
            options={
                'db_table': 'masshunter_configuracion',
                'unique_together': {('instrumento', 'metodo_cuantificacion')},
            },
        ),
    ]
